version: '3.8'
services:
  simwastasik-app:
    image: rikzafrontenddev/simwastasik:latest
    container_name: simwastasik-app
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    volumes:
      - .:/app
    restart: unless-stopped
